/**
	Generated by sails-inverse-model
	Date:Wed Jun 16 2021 11:33:54 GMT-0400 (Eastern Daylight Time)
*/


module.exports = {
    attributes: {
        currency: {
            type: 'string',
        },
        pays: {
            type: "string",

        },
        taux: {
            type: "string",
        },

        TVA: {
            type: 'string',
        }
    }
};